"""add mew column in base

Revision ID: 9325286ce82a
Revises: 
Create Date: 2025-10-06 21:01:39.447653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9325286ce82a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('album_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performers_stage_name'), 'performers', ['stage_name'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('singer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['singer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_performes_stage_name'), table_name='performes')
    op.drop_table('performes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('stage_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('album_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performes_stage_name'), 'performes', ['stage_name'], unique=1)
    op.drop_table('tracks')
    op.drop_index(op.f('ix_performers_stage_name'), table_name='performers')
    op.drop_table('performers')
    # ### end Alembic commands ###
